== Pipelines

To go faster developing Microservices its great to automate everything and have a _Continuous Deployment pipeline_ for each Microservice. The pipeline then defines how to:

* build your Microservice and create an immutable docker image for it with a unique version label
* generate or enrich the versioned Kubernetes manifest for your Microservice
* run link:../testing.html[system and integration tests] on your image to check its working correctly
* deploy your Microservice to an environment
* on approval deploy to the production environment

In *fabric8* we use https://jenkins.io/[Jenkins Pipelines] to implement the pipeline for each Microservice. The pipeline is defined in a file called `Jenkinsfile` which is checked into the source repository of each Microservice so that its versioned along with the implementation code.

To get started with your first pipeline, just create a new Microservice using the link:console.html[Developer Console] which will prompt you to pick a suitable
pipeline from the link:../jenkinsWorkflowLibrary.html[Reusable Pipeline Library]